DROP SCHEMA WTH;

CREATE SCHEMA WTH;

DROP TABLE WTH.AUDIENCE;

CREATE COLUMN TABLE WTH.AUDIENCE(NAME NVARCHAR(1000),NUM NVARCHAR(1000) PRIMARY KEY, LIKE NVARCHAR(1000), DISLIKE NVARCHAR(1000),FLAG NVARCHAR(1));

DELETE FROM WTH.AUDIENCE;
INSERT INTO WTH.AUDIENCE values ('SKILL INDIA','1','200','10','1');
INSERT INTO WTH.AUDIENCE values ('CSR','2','100','80','0');

