DELETE FROM "WTH"."AUDIENCE";
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,1,0,0,1);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,2,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,3,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,4,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,5,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,6,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,7,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,8,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,9,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,10,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,11,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,12,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,13,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,14,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,15,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,16,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,17,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,18,0,0,0);
INSERT INTO "WTH"."AUDIENCE" VALUES(COUNTER.nextval,19,0,0,0);


ALTER SEQUENCE COUNTER RESTART WITH 1;
ALTER SEQUENCE JUDGE_COUNTER RESTART WITH 0;

UPDATE "WTH"."AUDIENCE" SET "FLAG"=0 and "TEAM_NAME"=1;
UPDATE "WTH"."AUDIENCE" SET "FLAG"=1 and "TEAM_NAME"=2;